[project]
name = "dairy-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.4",
    "streamlit>=1.50.0",
    "streamlit-option-menu>=0.4.0",
]
